### ISSUE TITLE
How to configure log level for openvino execution provider?

### ISSUE THREAD

**Issue by jinmingyi1998** [intel/onnxruntime#137] opened 2022-02-16 03:31 UTC
How to configure log level for openvino execution provider?

I'm using onnxruntime with openvino execution provider, and i always get warnnings like this:
```
[WARN] 2022-02-16T03:23:10z frontend/onnx_import/src/core/graph.cpp 103
Could not create an nGraph Constant for initializer '738'. 
Constant with a 0 value was created, make sure connected input is optional.
Otherwise verify if the initializer contains a correct number of elements matching the initializer's shape. 
Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at core/include/ngraph/op/constant.hpp:59:
While validating node 'v0::Constant Constant_14387 () -> (f32{})' with friendly_name 'Constant_14387':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).
```

- I can get the correct result.
- I want to set log level to Error/Fatal. I dont want to see too much warnning log.
- I find nothing about log level in provider option. I set onnxruntime log level,  but it apply on ort log, this it still print a lot of warnning.

Please tell me how to set log level

**Comment by MaajidKhan** [comment] 2022-02-18 13:47
Hello @jinmingyi1998. We don't have anything to configure log level specific to OpenVINO EP execution. 

Looks like the warnings you are seeing are coming from the ONNX Importer component of OpenVINO.

Can you share more details here. What model you used and can you share the model with us to investigate.

Having said that, just wanted to let you know that these warnings won't have any impact on the inferencing time of the model. But, please share the model details, we will investigate and fix the issue.

**Comment by jinmingyi1998** [comment] 2022-02-21 01:53
> Hello @jinmingyi1998. We don't have anything to configure log level specific to OpenVINO EP execution.
> 
> Looks like the warnings you are seeing are coming from the ONNX Importer component of OpenVINO.
> 
> Can you share more details here. What model you used and can you share the model with us to investigate.
> 
> Having said that, just wanted to let you know that these warnings won't have any impact on the inferencing time of the model. But, please share the model details, we will investigate and fix the issue.

[epoch115.zip](https://github.com/intel/onnxruntime/files/8105571/epoch115.zip)

 As far as i known, this warning is casued by constant node - RESIZE.

Do you have any ideas to solve it ?

**Comment by MaajidKhan** [comment] 2022-02-24 05:40
Hi @jinmingyi1998 . we investigated the issue by running your model. The issue is coming from OpenVINO's ngraph component when the ONNX model is being imported by OpenVINO. The latest current version of OpenVINO is OpenVINO 2021.4.2 LTS. We have a upcoming new OpenVINO version 2022.1 release in Mar 2nd to 3rd week. The warnings will be fixed with this release.

**current status with OV 2021.4.2:**
![image](https://user-images.githubusercontent.com/29036417/155464617-f7861e0e-e02f-4e18-a440-69c9acd45930.png)


**With upcoming OV 2022.1 Release (Mar'2022):**
![image](https://user-images.githubusercontent.com/29036417/155464775-7fd0bf35-df75-4f60-9076-fa6a391a49be.png)


I hope the issue is answered. Pls close the ticket if you don't have any other questions.

**Closed by MaajidKhan** 2022-02-24 05:40 UTC

**Comment by jinmingyi1998** [comment] 2022-02-24 07:26
looking forward to new release!
